"""Canonical list of Lowe's store metadata for Washington and Oregon."""

from __future__ import annotations

LOWES_STORES_WA_OR: dict[str, dict[str, str]] = {
    # --- WASHINGTON ---
    "0061": {
        "name": "LOWE'S OF SMOKEY POINT, WA",
        "address": "3300 169th Place NE, Arlington, WA 98223",
        "city": "Arlington",
        "state": "WA",
        "zip": "98223",
    },
    "1089": {
        "name": "LOWE'S OF AUBURN, WA",
        "address": "1232 A Street NE, Auburn, WA 98002",
        "city": "Auburn",
        "state": "WA",
        "zip": "98002",
    },
    "1631": {
        "name": "LOWE'S OF BELLINGHAM, WA",
        "address": "1050 East Sunset Drive, Bellingham, WA 98226",
        "city": "Bellingham",
        "state": "WA",
        "zip": "98226",
    },
    "2895": {
        "name": "LOWE'S OF BONNEY LAKE, WA",
        "address": "19911 South Prairie Road E, Bonney Lake, WA 98391",
        "city": "Bonney Lake",
        "state": "WA",
        "zip": "98391",
    },
    "1534": {
        "name": "LOWE'S OF BREMERTON, WA",
        "address": "5600 State Highway 303 NE, Bremerton, WA 98311",
        "city": "Bremerton",
        "state": "WA",
        "zip": "98311",
    },
    "0149": {
        "name": "LOWE'S OF EVERETT, WA",
        "address": "2505 Pacific Avenue, Everett, WA 98201",
        "city": "Everett",
        "state": "WA",
        "zip": "98201",
    },
    "2346": {
        "name": "LOWE'S OF FEDERAL WAY, WA",
        "address": "35425 Enchanted Parkway S, Federal Way, WA 98003",
        "city": "Federal Way",
        "state": "WA",
        "zip": "98003",
    },
    "0140": {
        "name": "LOWE'S OF ISSAQUAH, WA",
        "address": "1625 11th Avenue NW, Issaquah, WA 98027",
        "city": "Issaquah",
        "state": "WA",
        "zip": "98027",
    },
    "0249": {
        "name": "LOWE'S OF KENNEWICK, WA",
        "address": "1020 North Colorado Street, Kennewick, WA 99336",
        "city": "Kennewick",
        "state": "WA",
        "zip": "99336",
    },
    "2561": {
        "name": "LOWE'S OF KENT-MIDWAY, WA",
        "address": "24050 Pacific Highway S, Kent, WA 98032",
        "city": "Kent",
        "state": "WA",
        "zip": "98032",
    },
    "2738": {
        "name": "LOWE'S OF S. LACEY, WA",
        "address": "5610 Corporate Center Lane SE, Lacey, WA 98503",
        "city": "Lacey",
        "state": "WA",
        "zip": "98503",
    },
    "1081": {
        "name": "LOWE'S OF LAKEWOOD, WA",
        "address": "5115 100th Street SW, Lakewood, WA 98499",
        "city": "Lakewood",
        "state": "WA",
        "zip": "98499",
    },
    "1887": {
        "name": "LOWE'S OF LONGVIEW, WA",
        "address": "2850 Ocean Beach Highway, Longview, WA 98632",
        "city": "Longview",
        "state": "WA",
        "zip": "98632",
    },
    "0285": {
        "name": "LOWE'S OF LYNNWOOD, WA",
        "address": "3100 196th Street SW, Lynnwood, WA 98036",
        "city": "Lynnwood",
        "state": "WA",
        "zip": "98036",
    },
    "1573": {
        "name": "LOWE'S OF MILL CREEK, WA",
        "address": "2002 132nd Street SE, Mill Creek, WA 98012",
        "city": "Mill Creek",
        "state": "WA",
        "zip": "98012",
    },
    "2781": {
        "name": "LOWE'S OF MONROE, WA",
        "address": "19393 Tjerne Place SE, Monroe, WA 98272",
        "city": "Monroe",
        "state": "WA",
        "zip": "98272",
    },
    "2956": {
        "name": "LOWE'S OF MOSES LAKE, WA",
        "address": "1400 East Yonezawa Boulevard, Moses Lake, WA 98837",
        "city": "Moses Lake",
        "state": "WA",
        "zip": "98837",
    },
    "0035": {
        "name": "LOWE'S OF MOUNT VERNON, WA",
        "address": "1717 Freeway Drive, Mount Vernon, WA 98273",
        "city": "Mount Vernon",
        "state": "WA",
        "zip": "98273",
    },
    "1167": {
        "name": "LOWE'S OF OLYMPIA, WA",
        "address": "4230 Martin Way E, Olympia, WA 98516",
        "city": "Olympia",
        "state": "WA",
        "zip": "98516",
    },
    "2344": {
        "name": "LOWE'S OF PASCO, WA",
        "address": "4520 North Road 68, Pasco, WA 99301",
        "city": "Pasco",
        "state": "WA",
        "zip": "99301",
    },
    "2733": {
        "name": "LOWE'S OF PORT ORCHARD, WA",
        "address": "150 SW Sedgwick Road, Port Orchard, WA 98367",
        "city": "Port Orchard",
        "state": "WA",
        "zip": "98367",
    },
    "2734": {
        "name": "LOWE'S OF PUYALLUP, WA",
        "address": "3511 5th Street SE, Puyallup, WA 98374",
        "city": "Puyallup",
        "state": "WA",
        "zip": "98374",
    },
    "2420": {
        "name": "LOWE'S OF RENTON, WA",
        "address": "1000 Garden Avenue N, Renton, WA 98057",
        "city": "Renton",
        "state": "WA",
        "zip": "98057",
    },
    "0252": {
        "name": "LOWE'S OF N. SEATTLE, WA",
        "address": "12525 Aurora Avenue N, Seattle, WA 98133",
        "city": "Seattle",
        "state": "WA",
        "zip": "98133",
    },
    "0004": {
        "name": "LOWE'S OF RAINIER, WA",
        "address": "2700 Rainier Avenue S, Seattle, WA 98144",
        "city": "Seattle",
        "state": "WA",
        "zip": "98144",
    },
    "2746": {
        "name": "LOWE'S OF SILVERDALE, WA",
        "address": "2221 NW Myhre Road, Silverdale, WA 98383",
        "city": "Silverdale",
        "state": "WA",
        "zip": "98383",
    },
    "3045": {
        "name": "LOWE'S OF N. SPOKANE, WA",
        "address": "6606 North Division Street, Spokane, WA 99208",
        "city": "Spokane",
        "state": "WA",
        "zip": "99208",
    },
    "0172": {
        "name": "LOWE'S OF SPOKANE VALLEY, WA",
        "address": "5204 East Sprague Avenue, Spokane, WA 99212",
        "city": "Spokane",
        "state": "WA",
        "zip": "99212",
    },
    "2793": {
        "name": "LOWE'S OF E. SPOKANE VALLEY, WA",
        "address": "16205 East Broadway Avenue, Spokane Valley, WA 99037",
        "city": "Spokane Valley",
        "state": "WA",
        "zip": "99037",
    },
    "0026": {
        "name": "LOWE'S OF TACOMA, WA",
        "address": "2701 South Orchard Street, Tacoma, WA 98466",
        "city": "Tacoma",
        "state": "WA",
        "zip": "98466",
    },
    "0010": {
        "name": "LOWE'S OF TUKWILA, WA",
        "address": "101 Andover Park E, Tukwila, WA 98188",
        "city": "Tukwila",
        "state": "WA",
        "zip": "98188",
    },
    "1632": {
        "name": "LOWE'S OF E. VANCOUVER, WA",
        "address": "11413 NE 76th Street, Vancouver, WA 98662",
        "city": "Vancouver",
        "state": "WA",
        "zip": "98662",
    },
    "2954": {
        "name": "LOWE'S OF LACAMAS LAKE, WA",
        "address": "18801 SE Mill Plain Boulevard, Vancouver, WA 98683",
        "city": "Vancouver",
        "state": "WA",
        "zip": "98683",
    },
    "0152": {
        "name": "LOWE'S OF WENATCHEE, WA",
        "address": "1200 Walla Walla Avenue, Wenatchee, WA 98801",
        "city": "Wenatchee",
        "state": "WA",
        "zip": "98801",
    },
    "3240": {
        "name": "LOWE'S OF YAKIMA, WA",
        "address": "2235 Longfibre Avenue, Yakima, WA 98903",
        "city": "Yakima",
        "state": "WA",
        "zip": "98903",
    },
    # --- OREGON ---
    "3057": {
        "name": "LOWE'S OF ALBANY - MILLERSBURG, OR",
        "address": "1300 9th Ave SE, Albany, OR 97322",
        "city": "Albany",
        "state": "OR",
        "zip": "97322",
    },
    "1690": {
        "name": "LOWE'S OF BEND, OR",
        "address": "20501 Cooley Road, Bend, OR 97701",
        "city": "Bend",
        "state": "OR",
        "zip": "97701",
    },
    "2940": {
        "name": "LOWE'S OF W. EUGENE, OR",
        "address": "3595 West 11th Avenue, Eugene, OR 97402",
        "city": "Eugene",
        "state": "OR",
        "zip": "97402",
    },
    "1558": {
        "name": "LOWE'S OF HILLSBORO, OR",
        "address": "1951 SE 24th Avenue, Hillsboro, OR 97123",
        "city": "Hillsboro",
        "state": "OR",
        "zip": "97123",
    },
    "2619": {
        "name": "LOWE'S OF KEIZER, OR",
        "address": "6225 Ulali Drive NE, Keizer, OR 97303",
        "city": "Keizer",
        "state": "OR",
        "zip": "97303",
    },
    "1693": {
        "name": "LOWE'S OF MCMINNVILLE, OR",
        "address": "1250 SW Booth Bend Road, McMinnville, OR 97128",
        "city": "McMinnville",
        "state": "OR",
        "zip": "97128",
    },
    "0248": {
        "name": "LOWE'S OF MEDFORD, OR",
        "address": "3601 Crater Lake Highway, Medford, OR 97504",
        "city": "Medford",
        "state": "OR",
        "zip": "97504",
    },
    "1824": {
        "name": "LOWE'S OF CLACKAMAS COUNTY, OR",
        "address": "13631 SE Johnson Road, Milwaukie, OR 97222",
        "city": "Milwaukie",
        "state": "OR",
        "zip": "97222",
    },
    "2579": {
        "name": "LOWE'S OF PORTLAND-DELTA PARK, OR",
        "address": "1160 N Hayden Meadows Drive, Portland, OR 97217",
        "city": "Portland",
        "state": "OR",
        "zip": "97217",
    },
    "2865": {
        "name": "LOWE'S OF REDMOND, OR",
        "address": "1313 SW Canal Boulevard, Redmond, OR 97756",
        "city": "Redmond",
        "state": "OR",
        "zip": "97756",
    },
    "1741": {
        "name": "LOWE'S OF ROSEBURG, OR",
        "address": "3300 NW Aviation Drive, Roseburg, OR 97470",
        "city": "Roseburg",
        "state": "OR",
        "zip": "97470",
    },
    "1600": {
        "name": "LOWE'S OF SALEM, OR",
        "address": "1930 Turner Road SE, Salem, OR 97302",
        "city": "Salem",
        "state": "OR",
        "zip": "97302",
    },
    "1108": {
        "name": "LOWE'S OF TIGARD, OR",
        "address": "12615 SW 72nd Avenue, Tigard, OR 97223",
        "city": "Tigard",
        "state": "OR",
        "zip": "97223",
    },
    "1114": {
        "name": "LOWE'S OF WOOD VILLAGE, OR",
        "address": "1000 NE Wood Village Blvd, Wood Village, OR 97060",
        "city": "Wood Village",
        "state": "OR",
        "zip": "97060",
    },
}
